### ISSUE TITLE
Invalid Win10x64_* Profiles

### ISSUE THREAD

**Issue by jpoling-dswrx** [volatilityfoundation/volatility#364] opened 2017-02-02 17:31 UTC
I've git cloned the latest repo/files today, but getting the following errors when attempting to use the Win10x64_10586 and Win10x64_14393 profiles for converting/decompressing a Win10 hibernation file from a Surface Pro. 

`# python vol.py --info | grep Win10`
>Volatility Foundation Volatility Framework 2.6
Win10x64              - A Profile for Windows 10 x64
Win10x64_10586        - A Profile for Windows 10 x64 (10.0.10586.306 / 2016-04-23)
Win10x64_14393        - A Profile for Windows 10 x64 (10.0.14393.0 / 2016-07-16)
Win10x86              - A Profile for Windows 10 x86
Win10x86_10586        - A Profile for Windows 10 x86 (10.0.10586.420 / 2016-05-28)
Win10x86_14393        - A Profile for Windows 10 x86 (10.0.14393.0 / 2016-07-16)
Win10AMD64PagedMemory         - Windows 10-specific AMD 64-bit address space.

`# vol.py -f /hiberfil.sys --profile=Win10x64_10586 imagecopy -O hiberfil.sys_conv_10586`
>Volatility Foundation Volatility Framework 2.5
ERROR   : volatility.debug    : Invalid profile Win10x64_10586 selected

`# vol.py -f hiberfil.sys --profile=Win10x64_14393 imagecopy -O hiberfil.sys_conv_14393`
>Volatility Foundation Volatility Framework 2.5
ERROR   : volatility.debug    : Invalid profile Win10x64_14393 selected

Am I perhaps missing something and/or doing something wrong?

**Comment by gleeda** [comment] 2017-02-02 18:42
We don't yet have hibernation file support in the current code base.
See issue #25 (https://github.com/volatilityfoundation/volatility/issues/25)

**Comment by jpoling-dswrx** [comment] 2017-02-02 19:15
Any suggestions for successfully decompressing hiberfiles from Win8+ systems in the meantime?

**Comment by gleeda** [comment] 2017-03-27 14:51
duplicate of issue #25

**Closed by gleeda** 2017-03-27 14:51 UTC
