### ISSUE TITLE
Windows8.1 no profile suggested 

### ISSUE THREAD

**Issue by dragosb91** [volatilityfoundation/volatility#218] opened 2015-05-21 11:09 UTC
I ran the imageinfo command on a x64 Windows 8.1 raw memory dump (only 3.5 GB RAM out of 4 GB RAM) and no profile was found for the it. I tried the same with Windows 7 SP1 x64 and I got some valid suggestions.
What could the problem be ? Thanks.

**Comment by iMHLv2** [comment] 2015-05-21 16:26
The problem is the encrypted kdbg structure on 64-bit win 8 and later. 

http://volatility-labs.blogspot.com/2014/01/the-secret-to-64-bit-windows-8-and-2012.html

Do volatility plugins work when you manually specify the profile (i.e. vol.py --profile=Win8SP0x64 pslist" ?

**Comment by dragosb91** [comment] 2015-05-21 17:22
They do not work. I am using the latest version of Windows 8 on the target machine. 
As a side note I am using the volatility windows binaries rather than the python files. I assume that is not relevant, but just to be aware of this.

**Comment by iMHLv2** [comment] 2015-06-03 16:46
I would suggest: 

* try the source version (there have been a number of updates since the last binary was released)
* try psscan instead of pslist (i.e. vol.py --profile=Win8SP0x64 psscan)

If all else fails and you happen to have access to the target system, can you zip the c:\windows\system32\ntoskrnl.exe file and post it somewhere we can download for analysis?

**Comment by iMHLv2** [comment] 2015-07-04 23:12
Hello, I'm going to close this out, because we'll need more information to pursue it. If you're able to get the ntoskrnl.exe from the system or try the additional steps I mentioned before, feel free to reopen.

**Closed by iMHLv2** 2015-07-04 23:12 UTC
