### ISSUE TITLE
Find cookies Firefox 46 LinuxOS

### ISSUE THREAD

**Issue by datquoc93** [volatilityfoundation/volatility#310] opened 2016-06-03 14:53 UTC

**Comment by datquoc93** [comment] 2016-06-03 15:01
https://github.com/datquoc93/VolatilityForensics/blob/master/datff.py

**Comment by gleeda** [comment] 2016-06-03 15:04
This seems to be a duplicate of issue #309 .  I'm going to close this one out

**Closed by gleeda** 2016-06-03 15:04 UTC
