### ISSUE TITLE
Win8.1x64 6.3.9600.16384 support

### ISSUE THREAD

**Issue by AddaxSoft** [volatilityfoundation/volatility#378] opened 2017-02-26 12:01 UTC
## Here is the scenario:

- I have a hibernation file `hiberfil.sys` for **Windows 8.1 6.3.9600.16384**
- I used volatility to convert to raw image with profile `Win8SP1x64_18340` and `Win8SP1x64`

## Results:
- `imageinfo` on both raw images I get `Suggested Profile(s) : No suggestion (Instantiated with no profile)`
- `hiberinfo` I also get: `No base Address Space`
- `kdbgscan` on both hiberfil and the converted image returns no results

![image](https://cloud.githubusercontent.com/assets/6898938/23339461/59eb6fd4-fc23-11e6-8a76-e9f9b935ff8b.png)

strings retrieve ASCII strings from `hiberfile.sys` file. 
The file doesn't seem to be corrupted.

![image](https://cloud.githubusercontent.com/assets/6898938/23339482/b65a5578-fc23-11e6-90d7-54575debd8ef.png)

**Comment by jared703** [comment] 2017-02-26 16:10
I don't think that Volatility handles 8.1 hiberfil.sys's currently (I could be off). @msuiche has [hibr2bin](https://github.com/comaeio/hibr2bin) that can convert it into a raw image that Volatility can then handle.

**Comment by AddaxSoft** [comment] 2017-02-26 16:54
thx @jared703  - I will try and report back :)

**Comment by AddaxSoft** [comment] 2017-02-26 17:59
hmm I get this - I've already submitted an issue https://github.com/comaeio/hibr2bin/issues/3 too. 

![image](https://cloud.githubusercontent.com/assets/6898938/23341946/47776528-fc51-11e6-9639-58f6985e5ce4.png)

**Comment by jared703** [comment] 2017-02-26 18:21
Assuming the syntax is correct, it looks like there is a potential error
with your hiberfil file itself.

**Comment by AddaxSoft** [comment] 2017-02-27 18:00
@jared703 why do you think that's the case? 
I can run `strings` and retrieve very detailed infos, plus the file size is almost 4gb.

**Comment by jared703** [comment] 2017-02-27 18:50
I'd recommend starting here:
https://www.504ensics.com/uploads/publications/modern-windows-hibernation.pdf
(Figure 5)to get an idea of what to expect in the file itself. There are
only a few tools now that handle the 8.1 hiberfil.sys files, so minus
creating something for yourself it's Hibr2bin (which failed for your
sample) and Arsenal's "Hibernation Recon" which I would also recommend
trying.

Something also to consider is that if your Hiberfil.sys was from an SSD,
according to Arsenal, is zero'd out upon system resume/wake:
https://twitter.com/ArsenalArmed/status/827580688186671105

**Comment by jared703** [comment] 2017-02-27 20:33
What's are the first 4 magic bytes in the header of your Hiberfil? I'm doing some testing now, but after running Hibr2Bin (3.0.20160920.100) against a sample with the WAKE magic, i'm gettting the same result as you (Error: the content of the hibernation file had been wiped out). Based on the research paper I linked above, it looks like their testing showed the the newer Hiberfil files were also zero'd out when the hiberfil had the WAKE magic.

**Comment by AddaxSoft** [comment] 2017-02-27 20:45
@jared703 I did see that word using strings, but here is the hexdump of the header!

![image](https://cloud.githubusercontent.com/assets/6898938/23379114/f7ed8380-fd35-11e6-9b7d-7a91c6d93a01.png)

**Comment by ArsenalSpencer** [comment] 2017-03-10 14:13
Can you try extracting the active contents of your hibernation file with our latest version and let me know how it goes? We added a "Free Mode" which will extract the active contents out into a physical memory dump. You will also get statistics related to the various kinds of slack within the hiberfil.sys and interesting NTFS metadata within both active contents and slack, should you want to go the hardcore route with your hibernation.

Here's a direct download link:

https://arsenalrecon.com/apps/download/HibernationRecon_1.1.0.55_Beta.zip

**Comment by AddaxSoft** [comment] 2017-03-10 16:20
@ArsenalSpencer I will, do you have a wiki / manpage for this tool?

**Comment by ArsenalSpencer** [comment] 2017-03-10 17:38
@AddaxSoft Just our product page so far:

https://arsenalrecon.com/apps/hibernation-recon/

It's basically point and shoot... you give Hibernation Recon a hiberfil.sys, and we take it from there.

**Comment by gleeda** [comment] 2017-03-27 14:47
Duplicate of issue #25

**Closed by gleeda** 2017-03-27 14:47 UTC
Labels: Win8
